properties:
  constant: 0.999755859375
  output0_select: 2
  output1_select: 7
  trigger_delay: 0.0
  trigger_mode: 1
submodules:
  aom_control:
    properties:
      feedback_enable: false
      feedback_gain: 0.0
      feedback_toggle_delay: 0.0
      feedback_toggle_time: 0.0
      input_select: 0
      trap_enable: true
      trap_toggle_delay: 5.0e-06
      trap_toggle_time: 3.0e-05
    submodules: {}
  delay_filter0:
    properties:
      ac_coupling: false
      constant: 0.0
      delay: 0.0
      gain: 0.9999997615814209
      input_select: 0
      output_select: 1
      preamp_gain: 1
      toggle_delay: 0.0
      toggle_time: 0.01
    submodules:
      biquad0:
        properties:
          filter_type: lowpass
          frequency: 1000.0
          q_factor: 10
        submodules: {}
      biquad1:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad2:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad3:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
  delay_filter1:
    properties:
      ac_coupling: true
      constant: 0.0
      delay: 0.0
      gain: 0.9999987483024597
      input_select: 1
      output_select: 0
      preamp_gain: 1
      toggle_delay: 0.001
      toggle_time: 0.0
    submodules:
      biquad0:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad1:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad2:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad3:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
  delay_filter2:
    properties:
      ac_coupling: true
      constant: 0.0
      delay: 0.0
      gain: 0.9999984502792358
      input_select: 0
      output_select: 0
      preamp_gain: 8
      toggle_delay: 0.001
      toggle_time: 0.0
    submodules:
      biquad0:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad1:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad2:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad3:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
  delay_filter3:
    properties:
      ac_coupling: true
      constant: 0.0
      delay: 0.0
      gain: 0.9999983906745911
      input_select: 0
      output_select: 0
      preamp_gain: 1
      toggle_delay: 0.001
      toggle_time: 0.0
    submodules:
      biquad0:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad1:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad2:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
      biquad3:
        properties:
          filter_type: allpass
          frequency: 100000.0
          q_factor: 10
        submodules: {}
  sum0:
    properties:
      add0: false
      add1: true
      add2: false
      add3: false
      add4: false
      add5: false
      add6: false
      add7: false
      divide_by: 1
    submodules: {}
  sum1:
    properties:
      add0: false
      add1: false
      add2: false
      add3: false
      add4: false
      add5: false
      add6: false
      add7: false
      divide_by: 1
    submodules: {}
  wavegen:
    properties:
      amplitude: 0.9999988675117493
      frequency: 2766.028046607971
    submodules: {}
